### ISSUE TITLE
Some dependencies should be devDependencies.  

### ISSUE THREAD

**Issue by garronej** [GouvernementFR/dsfr-chart#11]
Hello,

Thank you for creating this package!

@K4ST0R recently integrated it into **react-dsfr**: [Example](https://components.react-dsfr.codegouv.studio/?path=/docs/charts-barchart).

However, we've noticed that installing `@gouvfr/chart-dsfr` brings in around 250 additional packages, resulting in a total size of about 200MB in the `node_modules` folder.

To optimize this, it would be beneficial to move certain dependencies, such as `sass`, to the `devDependencies` list.

Best regards,

**Comment by zellerbaptiste** [comment]
Merci pour le retour @garronej nous allons nous pencher sur le sujet et voir ce qui peut être amélioré en ce sens pour la prochaine release.

**Comment by garronej** [comment]
Top merci
