### ISSUE TITLE
Amélioration du module Cartes > Découpage départemental pour sélectionner plusieurs départements

### ISSUE THREAD

**Issue by cecilaki** [GouvernementFR/dsfr-chart#3]
Hello, 

En vue d'une réutilisation pour le projet PILOTE. l'équipe DITP s'est penchée sur le repo et sur les types de charts proposés, notamment ceux concernant la cartographie. Nous sommes particulièrement intéressés par les modules de cartes et de découpage départemental. 

Néanmoins, nous souhaitons pouvoir proposer comme fonctionnalité la **sélection de plusieurs départements** à partir de la carte (pour afficher des informations dans une zone de texte qui n'est pas l'infobulle), ce qui n'est pas le comportement natif et actuel du widget. 

Pour l'instant nous allons donc développer notre propre module qui proposerait cette fonctionnalité dont nous avons besoin. 

Nous aurions cependant aimé proposer ce module dans le catalogue du DSFR Charts, quelle serait votre politique en matière de contribution et de maintenance de DSFR-Chart ? Sinon comment intégrer le développement de cette fonctionnalité dans la roadmap de DSFR-charts ?

Poke  @contitri

**Comment by zellerbaptiste** [comment]
Bonjour Cecile,
desolé pour le délais de réponse la librairie n'a pas beaucoup évolué depuis la release de la `v1.0.0` mais nous sommes en passe de sortir prochainement une `v1.1.0`

Merci pour votre proposition de contribution, le projet étant Open source les contributions et proposition d'evolution sont les bienvenues et vous trouverez toutes les instructions pour proposer une PR dans le fichier CONTRIBUTING.md à la racine du projet.

La sortie de la prochaine version pouvant faire évoluer quelque peu le code existant nous vous conseillons d'attendre cette dernière avant d'ouvrir une nouvelle PR.
