### ISSUE TITLE
Problème d'installation avec npm / yarn

### ISSUE THREAD

**Issue by bellangerq** [GouvernementFR/dsfr-chart#6]
Bonjour,

J'ai une erreur lorsque j'essaie d'installer la librairie avec npm ou yarn :

Avec npm :
```sh
npm ERR! code ENOVERSIONS
npm ERR! No versions available for dsfr-chart

npm ERR! A complete log of this run can be found in: /Users/quentin/.npm/_logs/2024-01-23T15_48_18_939Z-debug-0.log
```

Avec yarn :
```sh
yarn add dsfr-chart
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for "dsfr-chart". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Il semblerait que la librairie ne soit pas publiée sur npm. En effet, cette page renvoie une 404 : https://www.npmjs.com/package/dsfr-chart

**Comment by zellerbaptiste** [comment]
Bonjour,
merci pour votre retour, nous avons constaté que le package n'est plus publié sur NPM et allons faire le nécessaire pour le rendre à nouveau disponible prochainement.

En attendant sachez que les sources sont disponibles en téléchargement (par graph et en version complète) sur la page de release de la [v1.0.0](https://github.com/GouvernementFR/dsfr-chart/releases/tag/v1.0.0).

Nous reviendrons vers vous dès que le package sera à nouveau disponible via NPM.

**Comment by zellerbaptiste** [comment]
Bonjour,
nous avons publié le package sur NPM, la v1.0.0 est disponible sur : 
[DSFR-chart-1.0.0](https://www.npmjs.com/package/@gouvfr/dsfr-chart)

N'hésitez pas à nous faire vos retours,
je ferme ce ticket d'issue.
