### ISSUE TITLE
Ajouter le type "sunburst chart"

### ISSUE THREAD

**Issue by jmarcuzzi-IGN** [GouvernementFR/dsfr-chart#9]
Bonjour, 

Serait-il possible d'avoir un diagramme circulaire avec 2 niveaux ou plus pour améliorer le rendu pour des données multi-dimensions comme peut le faire le barchart ?

Merci

**Comment by zellerbaptiste** [comment]
Bonjour,
merci pour la proposition d'evolution, ce n'est pas une priorité dans notre backlog, toutefois la librairie DSFR-chart est ouverte à la contribution, vous trouverez toutes les instructions pour proposer une PR dans le fichier CONTRIBUTING.md à la racine du projet.
